### ISSUE TITLE
Scalapack and GNU 5.2

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS-Dependencies/scalapack#1]
From Hugh Sorby:
My gnu fortran compiler 5.2.0 cannot compile scalapack with the compiler flag:

-fipa-cp-clone

it causes an internal compiler error, this flag is used with 03 and Ofast optimisations, hopefully just an issue with this particular compiler.

**Comment by hsorby** [comment]
This issue has been addressed in #2
